### ISSUE TITLE
Support non-UTF8 filenames

### ISSUE THREAD

**Issue by rbran** [wcampbell0x2a/backhand#117]
Filenames can't be represented as String, because they maybe be not valid UTF8:

```bash
$ RUST_BACKTRACE=1 ~/src/backhand/target/release/unsquashfs -l non_utf8.squashfs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 9, error_len: Some(1) }', src/dir.rs:73:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: backhand::dir::DirEntry::name
   4: backhand::squashfs::Squashfs<R>::extract_dir
   5: backhand::squashfs::Squashfs<R>::into_filesystem_reader
   6: unsquashfs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rbran** [comment]
Assuming that this project is unix only (as `std::os::unix` is imported) the PL https://github.com/wcampbell0x2a/backhand/pull/118 should fix this.

But for a multi-platform solution, it will probably required to store all filenames as `Vec<u8>` and convert it into `PathBuf`/`String` only when the files are created/printed. If stored directly as `PathBuf`, on windows the the command `unsquashfs -l non_utf8.squashfs` will not work.

**Comment by rbran** [comment]
BTW here an file that creates a squashfs with non utf8 filenames https://gist.github.com/rbran/dbb8141356ca8c102183aa3b88b9ee2c

**Comment by wcampbell0x2a** [comment]
Thanks for the fix, I'm really only interested in linux support.
