### ISSUE TITLE
Bug in data extraction

### ISSUE THREAD

**Issue by wcampbell0x2a** [wcampbell0x2a/backhand#189]
@rbran, found a bug with data extraction again. Any quick ideas on how to fix it?
```
# squashfs-tools
$ unsquashfs test-assets/test_00/bytes.squashfs

# backhand
$ /target/release/unsquashfs test-assets/test_00/out.squashfs -d squashfs-root-rust
```

Looks like it reset back the beginning on the last(?) block:
![image](https://user-images.githubusercontent.com/15236002/224878908-e0f9d825-e5ad-40c9-bcd0-f3173652a31c.png)

**Comment by wcampbell0x2a** [comment]
I believe I fixed it with #191, I really should add tests for this...

**Comment by rbran** [comment]
Seems #191 fix the bug. But there are Some things that bothers me:

Functions `SquashfsReadFile::read_available` and  `SquashfsReadFile::read_next_block` should not be public, maybe also remove `SquahsfsReadFile::available`. Only trait `Read` should be accessible by the user.

The function `SquashfsRawData::decompress` assumes the `output_buf` is empty, maybe we should enforce that with a `assert!(output_buf.is_empty());`, same happens on the `compressor.rs` `decompress` function.

Let me know what you think. I can do the PR.

**Comment by wcampbell0x2a** [comment]
Agreed, I had to look through the code quite hard to see that it expects that buffer to be empty.

unreachable might be better? Idk if the compiler treats that codegen better?

You can do it if you want.
