### ISSUE TITLE
BasicFile is not documented or linked in rustdocs

### ISSUE THREAD

**Issue by detly** [wcampbell0x2a/backhand#194]
Looking at eg. the [`SquashFsFileReader` docs](https://docs.rs/backhand/0.10.1/backhand/struct.SquashfsFileReader.html), for 0.10.1 I see:

![Screenshot from 2023-03-14 22-00-16](https://user-images.githubusercontent.com/311239/225025018-d266f2e7-9104-4115-bdf4-82eb709b13c5.png)

The `BasicFile` docs aren't anywhere in the generated documentation, which makes it very hard to figure out what to actually *do* with a `SquashFsFileReader`.

**Comment by wcampbell0x2a** [comment]
See https://github.com/wcampbell0x2a/backhand/pull/195, although https://github.com/wcampbell0x2a/backhand/pull/196 will help unless you have a different use case.
