### ISSUE TITLE
extract-backhand utility?

### ISSUE THREAD

**Issue by fullspectrumdev** [wcampbell0x2a/backhand#234]
Given there is already `add-backhand` and `replace-backhand` (super useful btw!), and a general purpose uncompressor tool, it would be nifty to have a `extract-backhand` that can yank a single file from a squashfs without having to unpack the whole thing.

Usecase: extracting a specific binary or file to modify and then shovel back in, for scripting :)

**Comment by wcampbell0x2a** [comment]
I added `--path-filter` to `unsquashfs` which should address your needs. Let me know if you see anything wrong.

**Comment by fullspectrumdev** [comment]
Will do some tests today!

**Comment by wcampbell0x2a** [comment]
Closing, let me know if this issue wasn't fixed.
