### ISSUE TITLE
Getting `thread 'main' panicked at 'called Option::unwrap() on a None value'`

### ISSUE THREAD

**Issue by hwittenborn** [wcampbell0x2a/backhand#275]
I'm getting this error whenever I try to create a SquashFS image in my application:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hunter/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backhand-0.13.0/src/entry.rs:49:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I was also able the reproduce the issue with the following code:

```rust
let mut writer = std::io::Cursor::new(vec![]);
let mut fs = backhand::FilesystemWriter::default();
fs.write(&mut writer).unwrap();
```

**Comment by wcampbell0x2a** [comment]
Good find. I'm not at my computer but 

https://github.com/wcampbell0x2a/backhand/blob/96c83729a791526ff0a3fd8e9390740c25ae8184/src/filesystem/writer.rs#L94

Should instead call:

https://github.com/wcampbell0x2a/backhand/blob/96c83729a791526ff0a3fd8e9390740c25ae8184/src/id.rs#L17

**Comment by wcampbell0x2a** [comment]
https://github.com/wcampbell0x2a/backhand/pull/276 should fix this

**Comment by hwittenborn** [comment]
Thank you @wcampbell0x2a! I'll go ahead and try running that branch in my program.

**Comment by hwittenborn** [comment]
Can confirm the PR fixed the issue, thanks a ton @wcampbell0x2a! Feel free to close the issue whenever it's best for you.
