### ISSUE TITLE
Publish new release on crates.io?

### ISSUE THREAD

**Issue by queer** [wcampbell0x2a/backhand#405]
Hello (: The latest release on crates.io is 0.13.0, from June 2023. Since then, some useful PRs (#365, #364, #360, etc.) have been merged. It would be lovely if we could get these without having to use a git dependency.

**Comment by wcampbell0x2a** [comment]
I hope to release sometime this week, all that I see left is some documentation.

Just curious, what project is this?

**Comment by queer** [comment]
> Just curious, what project is this?

I've been working on adding squashfs support to https://github.com/queer/peckish!

**Comment by wcampbell0x2a** [comment]
Sweet!

Released: https://github.com/wcampbell0x2a/backhand/releases/tag/v0.14.0

**Comment by queer** [comment]
Awesome, thank you :D
