### ISSUE TITLE
Failed to compilec on MacOS

### ISSUE THREAD

**Issue by itrack** [wcampbell0x2a/backhand#506]
**cargo install backhand-cli --locked**

`error[E0277]: the trait bound `i32: From<u32>` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backhand-cli-0.14.2/src/bin/unsquashfs.rs:564:25
    |
564 |                         dev_t::from(*device_number),
    |                         ^^^^^ the trait `From<u32>` is not implemented for `i32`
    |
    = help: the following other types implement trait `From<T>`:
              <i32 as From<bool>>
              <i32 as From<i8>>
              <i32 as From<i16>>
              <i32 as From<u8>>
              <i32 as From<u16>>
              <i32 as From<errno::Errno>>
              <i32 as From<NonZeroI32>>

error[E0277]: the trait bound `i32: From<u32>` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backhand-cli-0.14.2/src/bin/unsquashfs.rs:606:21
    |
606 |                     dev_t::from(*device_number),
    |                     ^^^^^ the trait `From<u32>` is not implemented for `i32`
    |
    = help: the following other types implement trait `From<T>`:
              <i32 as From<bool>>
              <i32 as From<i8>>
              <i32 as From<i16>>
              <i32 as From<u8>>
              <i32 as From<u16>>
              <i32 as From<errno::Errno>>
              <i32 as From<NonZeroI32>>

`

<img width="965" alt="Screenshot 2024-03-20 at 00 06 17" src="https://github.com/wcampbell0x2a/backhand/assets/2368391/65adb976-db5f-4869-a187-e21415221122">

MacOS OS 14.3.1

Any idea what could be the problem?
Thank you!

**Comment by wcampbell0x2a** [comment]
There was an older MR that fixed it previously, all it took was changing those calls to `try_from` instead of `from`: https://github.com/wcampbell0x2a/backhand/pull/260


Should be easy! Now that github has macos runners, I should be able to test and build in ci: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by itrack** [comment]
I have seen this MR, the error occurs when installing the latest version with the command "cargo install backhand-cli --locked"
The error probably hasn't been fixed yet

**Comment by wcampbell0x2a** [comment]
I should have the problem fixed with: #511 

I also have the binaries tested and building in CI if you wanna test out the release binary: https://github.com/wcampbell0x2a/backhand/actions/runs/8488262471/artifacts/1371054272

**Comment by wcampbell0x2a** [comment]
Closing, should be fixed.
